version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safezone_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/safezone_db
      SECRET: SAYSAMONE1
      CLOUDINARY_CLOUD_NAME: dnplboikb
      CLOUDINARY_API_KEY: 298611556276172
      CLOUDINARY_API_SECRET: s-s-vdRpifR_1slH-EXvz2Ha2Mx4o-EXvz2Ha2Mx4o
    depends_on:
      - db

volumes:
  db-data:
